global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-svc.shamba.svc.cluster.local:8000']
  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend-svc.shamba.svc.cluster.local:80']
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
