apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shamba-ingress
  namespace: shamba
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - app.shamba.ai
        - api.shamba.ai
      secretName: shamba-tls
  rules:
    - host: api.shamba.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8000
    - host: app.shamba.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
