apiVersion: v1
kind: Secret
metadata:
  name: shamba-secrets
  namespace: shamba
type: Opaque
data:
  DB_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk
  JWT_SECRET: c2VjdXJlX2p3dA==
  MAPBOX_TOKEN: eW91cl9tYXBib3hfdG9rZW4=
