apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: shamba
spec:
  selector:
    app: shamba-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: shamba
spec:
  selector:
    app: shamba-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
